apiVersion: v1
kind: Pod
metadata:
  name: kafka-consumer
spec:
  containers:
  - name: kafka-consumer
    image: bitnami/kafka:latest
    command:
    - sh
    - -c
    - |
      kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic demo-topic --from-beginning --timeout-ms 5000
  restartPolicy: Never
