apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        ports:
        - containerPort: 9092
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer
  namespace: kafka
spec:
  containers:
  - name: kafka-producer
    image: bitnami/kafka:latest
    command:
    - sh
    - -c
    - |
      # Sleep to wait for Kafka to start
      sleep 10
      echo "kafka-producer"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-consumer
  namespace: kafka
spec:
  containers:
  - name: kafka-consumer
    image: bitnami/kafka:latest
    command:
    - sh
    - -c
    - |
      # Sleep to wait for Kafka to start
      sleep 10
      echo "kafka-consumer"
  restartPolicy: Never

