apiVersion: v1
kind: Pod
metadata:
  name: kafka-topic-creator
spec:
  containers:
  - name: kafka-topic-creator
    image: bitnami/kafka:latest
    command:
    - sh
    - -c
    - |
      kafka-topics.sh --create --topic demo-topic --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1
  restartPolicy: Never
