apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-editor
  labels:
    app: swagger-editor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-editor
  template:
    metadata:
      labels:
        app: swagger-editor
    spec:
      containers:
      - name: swagger-editor
        image: swaggerapi/swagger-editor:latest
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-editor
spec:
  type: NodePort
  selector:
    app: swagger-editor
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30000  # This is the port you will access externally
